### ISSUE TITLE
关于变量填写

### ISSUE THREAD

**Issue by myh1990** [Y80/bmm#14]
请教下，fork之后，这个四个变量（DB_CONNECTION_URL、AUTH_URL、AUTH_GITHUB_SECRET 和 AUTH_GITHUB_ID）在哪里获取啊，方便出个简单教程么

**Comment by Y80** [comment]
README 写了呀，是有哪里没看明白吗

**Comment by myh1990** [comment]
哇，回复好快，感谢，就是这四个环境变量后面的值不知道怎么获取，我是直接fork之后从vercel里导入部署，然后直接deploy就是失败，我的理解是不是得提前先设置好环境变量的这四个值，但是不知道从哪个地方获取，readme我看过了，但是不知道这个值是怎么创建出来的

**Comment by myh1990** [comment]
![image](https://github.com/user-attachments/assets/a4e2b2fd-8894-48c8-971c-2083a6bf74e8)
就是这个地方，我如果直接点部署的话肯定是失败，然后但是这几个变量不知道咋获取或者创建的，我只大概知道最后一个应该是在github那个设置里创建的。

**Comment by Y80** [comment]
变量的获取可参考 [README: 准备内容](https://github.com/Y80/bmm?tab=readme-ov-file#%EF%B8%8F-%E5%87%86%E5%A4%87%E5%86%85%E5%AE%B9)，这里几个变量如何获取、有何用途我已经尽我所能讲得很详细了。

但是如果你连「数据库连接 URL」是什么都不清楚的话，那我这边确实也帮不了什么，还是建议先学习下相关的基础知识。

**Comment by myh1990** [comment]
好的，收到了，谢谢

**Comment by myh1990** [comment]
好的，收到了，谢谢
