### ISSUE TITLE
vercel部署报错，如何解决

### ISSUE THREAD

**Issue by lihuikun** [Y80/bmm#16]
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3717409929

**Comment by Y80** [comment]
可以贴下 server logs 吗

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/81033585-b67c-4162-8d5e-b254421d90db)

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/39f0673c-552c-4e72-98bd-a87c52b68579)控制台报错500~

**Comment by Y80** [comment]
看样子是数据库初始化失败了。

请确保你配置的环境变量 `DB_CONNECTION_URL` 是可用的。

然后你可以尝试如下几种方案：

- 在 Vercel 中重新部署项目
- 更换数据库连接 URL，重新部署项目
- 将项目拉到本地，手动执行 `pnpm tsx scripts/db-init.zx -P` 初始化正式环境的数据库

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/c948caf7-320c-4f97-af10-c79a78b39aca)
1、2都弄了，是更改[YOUR-PASSWORD]这里，包括[]也要去掉？是否还要初始化其他

**Comment by Y80** [comment]
你需要把 `[YOUR-PASSWORD]` 整块都替换为你的数据库密码。

更多资料可咨询 Google / ChatGPT ：PostgreSQL 数据库连接 URL

**Comment by lihuikun** [comment]
是的，已经替换了，还是不行，试试第三点，本地手动执行 pnpm tsx scripts/db-init.zx -P 初始化正式环境的数据库，这里要改本地的环境变量？是需要改哪一个文件

**Comment by Y80** [comment]
`.env` 文件中的 `DB_CONNECTION_URL`

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/f7bba76e-152c-499f-a78d-1308c0042889)
还是失败，看看是不是这样~

**Comment by Y80** [comment]
出现这个，表明你的数据库连接是没问题的。

WSL ERROR 你可以参考下这个 https://github.com/google/zx/issues/761

**Comment by lihuikun** [comment]
可以了，我使用git bash进行命令执行~感谢大佬

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/336ab0bd-674a-4686-a41f-e63c9e7b7eb3)
ggithub登录之后，这里是要设置啥？

**Comment by Y80** [comment]
浏览器 URL 怪怪的。你是通过 https://bmm-six.vercel.app 访问的吗

**Comment by lihuikun** [comment]
是的，登录之后就报上面那个错

**Comment by Y80** [comment]
可以尝试一下清除浏览器 cookie、重新登录

**Comment by lihuikun** [comment]
还是一样的，是不是github配置问题~

**Comment by Y80** [comment]
<img width="874" alt="image" src="https://github.com/user-attachments/assets/fec7adba-e56a-4fe2-bd05-5aa1999aaeca">

配置就是这么配置。

也可以去数据库 User 表中查看是否创建了刚刚 Github 授权用户的对应的记录。

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/e5bde17e-c5cd-4889-9ca4-7a7e23ab2b53)
有的，但是进不去

**Comment by Y80** [comment]
你可以尝试在一个新的浏览器中打开 `/login` 页面，重新登录

**Comment by lihuikun** [comment]
还是一样的，跳到admin，报401

**Comment by Y80** [comment]
我刚才 commit 了一次代码，你 pull 一下，然后再重试一下。

新的代码将会在检测到用户没有登录时，重定向至 `/login` 页面。

**Comment by lihuikun** [comment]
还是不行，登录好像不成功，一直跳到login页面

**Comment by Y80** [comment]
额。那也太奇怪了。看看浏览器和终端有没有什么报错信息吧。

这个文件的 debug 可以开启一下，可以查看详细的日志信息

<img width="546" alt="image" src="https://github.com/user-attachments/assets/373a5ba6-f616-4e67-9b13-8c11271f849e">

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/f372b363-13d6-4c1a-8ebc-b37549bd0b40)
报错信息~

**Comment by Y80** [comment]
Vercel 环境变量中，你定义一下 AUTH_SECRET 呢？

**Comment by lihuikun** [comment]
值是啥？

**Comment by Y80** [comment]
用一个随机生成的 uuid

**Comment by lihuikun** [comment]
![image](https://github.com/user-attachments/assets/5ed5502f-442c-49e0-95c4-c980bdb2e2ff)
hai'shi还是不行哦

**Comment by Y80** [comment]
记得重新部署一下

**Comment by lihuikun** [comment]
可以了，感谢大佬指点~
