### ISSUE TITLE
功能请求~

### ISSUE THREAD

**Issue by white0dew** [Y80/bmm#17]
1、增加链接访问次数
2、增加分组功能，举个例子，我想单独建立一个书签页面，叫做视频，那么这个url链接就是site_url/video，图片等等同理，这样我们就可以进行分组的管理啦

**Comment by Y80** [comment]
1. 这个实现倒是不难，但是这个数值统计出来有什么使用场景？

2. 有考虑过，但是交互、数据结构方面需要好好想一下；这个我会加到 roadmap 里的
