### ISSUE TITLE
Vercel 部署后访问不了

### ISSUE THREAD

**Issue by hezi-repo** [Y80/bmm#18]
我根据文档在Vercel部署了, 首次访问报错, 看日志是:
c: relation "publicBookmarks" does not exist

可能是数据库没有建表, 但是项目没找到初始建表的文件.

**Comment by Y80** [comment]
可以先检查下 Vercel 上的构建日志是否有异常
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/5509b012-f6ff-4b85-b237-41ce0743caf2">

**Comment by hezi-repo** [comment]
打扰了, 我上去supabase 确认没有数据库, 自己在本地执行 tsx scripts/db-init.zx 就可以了
