### ISSUE TITLE
【搜索bug】第一次搜索后会失焦

### ISSUE THREAD

**Issue by nsnans** [Y80/bmm#5]
## bug描述
看搜索框输入，第一次输`a`，搜索后搜索框会失焦，后面再输入`a`搜索，却不会失焦

![recording](https://github.com/user-attachments/assets/5fcc2f4b-a535-481d-b864-cd0678ddb5e8)

**Comment by Y80** [comment]
感谢反馈这个交互细节，已经优化啦
