### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by wuchen00** [Y80/bmm#7]
数据库配置那里，一开始没有数据库，想用作者说的免费云，但是没有看到哪里可以还原数据库

**Comment by Y80** [comment]
> 数据库配置那里，一开始没有数据库，想用作者说的免费云，但是没有看到哪里可以还原数据库

「还原数据库」是指什么呢？是指重置数据库还是其他什么呢

**Comment by wuchen00** [comment]
我理解的是这个项目一开始要创建一个初始数据库？里面还有一些表结构什么的，但是我现在搞了一个免费云，里面就一个库，没有表之类的，所以看有没有sql文件可以直接生成表数据
除了这个之外，数据库链接那里只填一个链接不对吧，有没有详细一点的说明

**Comment by Y80** [comment]
@wuchen00 
写了篇 Wiki 介绍了下
https://github.com/Y80/bmm/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E5%88%9D%E5%A7%8B%E5%8C%96
